name: Documentation using Sphinx

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the code
              uses: actions/checkout@v2
            
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                    python-version: 3.10.12

            - name: Install Dependencies
              run: pip install -r requirements.txt

            - name: Build Documentation Sphinx
              run: |
                cd docs
                sphinx-build -b html . _build