name: continuos-integration with GitHub Actions

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout do código
              uses: actions/checkout@v2

            - name: Configurar Ambiente Python
              uses: actions/setup-python@v2
              with:
                    python-version: 3.10.12
            
            - name: Instalar Poetry
              run: |
                curl -sSL https://install.python-poetry.org | python3 -
            
            - name: Configurar cache do Poetry
              uses: actions/cache@v2
              with:
                    path: ~/.cache/pypoetry
                    key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-poetry-
            
            - name: Instalar dependências
              run: poetry install

            - name: Build do projeto
              run: poetry build
